### ISSUE TITLE
Add PhatLoots Support

### ISSUE THREAD

**Issue by vintagedon** [orphu/mcdungeon#159]
PhatLoots is an amazing treasure chest plugin that I use quite extensively.  It's actively maintained and allows you to set random items that are of random enchantment levels (you can specify a range) that appear in "loot chests".  It will also name these items according to rarity levels and the enchantment type.  Finally, you can set regeration times so that once emptied, the chests refill.

Hooking into this would give the dungeons replay value, and bring a new dimension to the generated dungeons.  CityWorld generator already hooks into PhatLoots for this.

**Comment by sshipway** [comment]
The PhatLoots plugin works by attaching to the chestGenHook() Minecraft function (I think), which is called by the terrain generator when it needs to have a chest.  There are several different chest types it can create and it is called once only, when the chunk is created.

This means that it is impossible for MCDungeon to support this, since the chestGenHook (and therefore the PhatLoots generator) is only available in-game, not externally.

In any case, custom loot tables are already supported by MCDungeon, and so these can be customised to give larger loot chests at the various levels if required.

I think this tciked can be closed?

(Ive been working on Minecraft plugins recently and come across this hook)

**Comment by JiFish** [comment]
Yes, this should have probably been closed some time ago. There's nothing we can do about this unless PhatLoots specifically allows us to place the chests via a tag in the world file.
