### ISSUE TITLE
New door images appear to be missing

### ISSUE THREAD

**Issue by MikeyCarter** [orphu/mcdungeon#278]
img src="d/197-8.png"
img src="d/196-1.png"
img src="d/196-8.png"

Finding tags like this don't appear to have images.  From there placement I'm assuming they're doors.

![selection_20150202_14 15 42_001_e2](https://cloud.githubusercontent.com/assets/1325499/6007135/0611fb7a-aae6-11e4-8079-1ea27dd0ea10.png)

**Comment by JiFish** [comment]
Whoops. This is my fault.

**Comment by JiFish** [comment]
I've added copies of the normal wood door to fix this. I figure this is okay since the map is just representative and the doors would be difficult to tell apart from above.

If anyone wants to make fancier versions, they are welcome!

To save anyone the trouble of doing this themselves in their local copies, I have provided a zip you can unpack to the d folder: http://files.jifish.co.uk/missing_doors.zip

**Comment by MikeyCarter** [comment]
Found another:  d/168-2.png 404 (Not Found)

**Comment by JiFish** [comment]
The underwater dungeon blocks are also missing. I'm on it.

**Comment by JiFish** [comment]
Fixed a number of missing images. Updated zip here: http://files.jifish.co.uk/missing_d_images.zip
