### ISSUE TITLE
Spawn Eggs as treasure broken in 1.9

### ISSUE THREAD

**Issue by orphu** [orphu/mcdungeon#331]
They appear as white eggs that just say "Spawn" and cannot be thrown. 

This is due to spawn eggs no longer using the damage value and now requiring an EntityTag.

**Comment by orphu** [comment]
Wish I could add a new "Special Flag" to items.txt that just passed through an arbitrary NBT structure. 

Can't think of a good way to handle that while dealing with all the NBT types, so I'll probably just add a new special flag for adding an EntityTag.

**Comment by JiFish** [comment]
Another option is to make the eggs nbt files like heads.

**Comment by orphu** [comment]
Oh, I'm torn. 

Updating all those spawner NBT files for 1.9 was a pain. Made me wish we were doing it all programmatically via helper functions in utils.

**Comment by JiFish** [comment]
In retrospect, it may have been better to parse nbt from strings (like command blocks work) rather than using raw nbt data.

The original purpose of the nbt files was so that special loading/rules weren't need for every possible item type. This seems like a case of that. That said, editing files is easier on the end-users.

Tough call... :)

**Comment by orphu** [comment]
I went with a new special in items.txt that adds an EntityTag.
