### ISSUE TITLE
Torch blocks with a data value of 0 result in invisible torches.

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#338]
This one is odd, and it might be OK to leave it in place as a 'feature'

The circle-of-skulls landmark seems to generate with an invisible lightsource in the centre.  This is visible if you view it at night.  I can't see anything in the code that should do this; it is not the spawner (as destroying the spawner does not remove the light source); and it does not seem to occur with any other landmarks.

I'll have to see if this was present under other versions in the past as well.

**Comment by orphu** [comment]
This also occurs with the dungeon version of Circle of Skulls. Looks liek it's due to the torches being added with a dv of zero. MC used to reset these to standing torches, but now it makes them invisible. 

This happens in a few places in the code, and should probably be fixed elsewhere. 

Secret room mechanisms is another one. 

Maybe make the default dv 5.

**Comment by orphu** [comment]
On testing, this will need to be looked at closely everywhere there is a torch being set without a dv. 

If the default is changed to 5, a torch will fall to the ground if it's not sitting on a block. So each instance will need to be looked at to make sure it's working.

**Comment by orphu** [comment]
Problem with setting the default to 5: It causes the inventory version of the torch to have an undefined texture.

**Comment by sshipway** [comment]
Pull req #342 fixes this for the Well landmark as well
