### ISSUE TITLE
Some entities not generating in pre-1.9 chunks

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#350]
Shopkeepers don't seem to be generating for me. I've tried both the master and development branch. And both minecraft 1.9.0 and 1.9.2. The rooms are empty, other mobs are spawning OK.

Here's the config I was testing with: http://pastebin.com/raw/SSXhNQJR

Can anyone confirm this?

**Comment by orphu** [comment]
Multiplayer or Singleplayer?

**Comment by orphu** [comment]
Tested in SP under 1.9.2 and had shopkeepers. Will also try MP.

**Comment by JiFish** [comment]
SP. I can't understand this. I generated dungeons a dozen times. Maybe the world file I was generating on is relevant instead of my config?

I will try again when I get back from work.

**Comment by JiFish** [comment]
It looks like it is the world file. I use a flatlands world for basic testing and I just copy it each time. The flatlands I generated in 1.9 work great, but the one I generated in an earlier version is missing shopkeepers. This persists even if I load the map in 1.9 before generating the dungeon.

Here's a link to the world in question: [mcd_base_old.zip](https://github.com/orphu/mcdungeon/files/207323/mcd_base_old.zip)

I'm not sure if there's much that can be done about this. But it might potentially mean this issue will occur in any maps first created in old minecraft versions?

**Comment by orphu** [comment]
That is concerning. I have no idea what we could do about it. The entities we create are the same. 

Unless the chunks need to be loaded and saved in 1.9? Just because you load a map doesn't mean you load in every chunk and save them out. The dungeon might be created in far off chunks. You'd have to travel to the chunks to get them updated. Maybe since we are essentially modifying "old" chunks saved under a previous version before 1.9 has any chance to correct them causes this?

**Comment by JiFish** [comment]
For my tests I didn't explore around in 1.9 before quitting. So that sounds like a likely theory. Seems like this would be most problematic for users that are re-generating dungeons on older maps.

The chunk DataVersion tag might be able to help. We could have MCDungeon refuse to generate dungeons in chunks that don't match the minimum DataVersion needed. At least the user could then fix the issue by wandering around the intended area in 1.9. https://www.reddit.com/r/MinecraftCommands/comments/3gsx1r/all_about_the_dataversion_tag

Unless there's a tool that updates your whole map? I wonder how MCEdit is dealing with this. (If they have to at all.)

If it were possible to re-generate chunks we could give an option to nuke and re-generate chunks before dungeon generation.

If nothing can be done, this phenomenon should be documented in the FAQs.

**Comment by orphu** [comment]
Oh, checking for a minimum data version tag is a great idea.

**Comment by sshipway** [comment]
If you can check the dataversion, then maybe write the objects in 1.8-format on old-format chunks, and 1.9-format in new-format chunks?  Seems that MC will automigrate the chunk to 1.9 the first time it is opened, and if it finds 1.9-format objects then these fail to migrate.  Of course, simply refusing to use old-format chunks works as well (but then a clear message to the user that they have 90% unusable old-version chunks in their world would be a good idea)

There's a good chance that the auto-generation mods -- worldborder for bukkit, or my own forge worldgen mod -- will trigger the chunk upgrade when they check the chunks.  I should check this but currently I'm way too overcommited to be able to start contributing to mcd again :(

**Comment by JiFish** [comment]
> If you can check the dataversion, then maybe write the objects in 1.8-format on old-format chunks, and 1.9-format in new-format chunks?

I think that's a can of worms. The reason DataVersion was introduced is so they can do things like this more easily in the future. Keeping heaps of legacy code around is the same reason we don't support generating for old versions (even by configuration options.)

It will definitely be an annoyance for some use cases, but I think a good error is the best we can do.

> (but then a clear message to the user that they have 90% unusable old-version chunks in their world would be a good idea)

Yeah, that would be handy. But I was thinking rather than scanning the whole map, you'd just scan the area you are about to place a dungeon in.

A script that shows chunk versions by percentage could be written as an extra. But this would just help out people that want to fix the whole world manually. You'd think most people would be looking to automate, e.g. a bukkit plugin like you mentioned.

**Comment by sshipway** [comment]
Would you not include chunk version scanning into the Good Chunks cache scanning?  When a chunk cache is created you get a list ofchunks separated by high/low/occupied/good/edge etc, so adding an 'old' category to this would solve the issue... as long as a chunk being updated increments the last-modified time so that the cache can be updated as well

**Comment by JiFish** [comment]
I'm not particularity familiar with the chunk scanning stuff, so that might be a good way to do it. It would certainly solve the issue without bothering the user (at the cost of some viable map space.)

But am I correct in thinking it would not solve the issue in cases of re-generating old dungeons in old maps? And also in cases where the user has manually chosen the dungeon location? (For that matter, what _currently_ happens when a user manually places a dungeon in a 'bad' chunk?)

**Comment by JiFish** [comment]
Note, the title still refers to shopkeepers, but this may effect other entities e.g. armoury guardians. Need to test that.

To confirm we are actually correct in our current thinking we should test by:
- Taking the above posted example map
- Updating all the chunks somehow (script? manually?)
- Trying to generate some shops.

**Comment by sshipway** [comment]
Doing it in the chunk-scanning code would make it very clear to the user if old chunks were blocking dungeon placement, rather than only telling them when they try to place a dungeon.  It might also be helpful for mcdungeon to have a separate command that displays the chunks cache stats - the breakdown of numbers of different chunks statuses, how many free, and so on - but that's probably a separate issue.

A regenerate would likely fail (if the chunk was old format) so you'd likely have to do a second test for chunk version before regenerating just in case, which may also apply to explicit locations.  However I think it would still be a more elegant solution to check primarily in the chunk cache and only check before placing as a 'belt and braces' verification.

(this is the sort of stuff I post when trying to avoid writing detailed systems design and business case documents :P )

**Comment by JiFish** [comment]
That sounds reasonable to me.

Still if it's chunk scanning and cache stuff, I think @orphu will have to look at this. I've basically never touched that bit of the code. ;)

**Comment by orphu** [comment]
Yeah, no, this gets back to trying to maintain code for every version on Minecraft going back forever. No way. 

I'm thinking a new category of chunks in the san step. "OldChunks" or something. And a message if this is a high percentage. 

How a user goes about fixing this I'm not sure. They would need to fly around the map, or get a mod to load the chunks for them. No way to easily work around it in vanilla. 

I'm betting this is the problem though. If a chunk gets loaded as an old version, MC applies different logic to loading the entity. In our case we have 1.9 format entities in a pre 1.9 chunk so the entity parser probably barfs on it because the structures are not correct.

>But am I correct in thinking it would not solve the issue in cases of re-generating old dungeons in old maps? And also in cases where the user has manually chosen the dungeon location? (For that matter, what currently happens when a user manually places a dungeon in a 'bad' chunk?)

You are correct. Also, if a user manually picks a location, the dungeon is placed no matter what. There may be unexpected results if MCD tries to bury the dungeon and things like that. In some cases it may not be possible, for instance if they try to place a dungeon where there are no chunks an error will occur. 

We can try updating the DataVersion tag ourselves for chunks we touch. In theory all the entities in those chunks are ours. That might avoid them being mishandled by MC. I don't know if this will take some modification of PyMcLevel.

**Comment by sshipway** [comment]
Probably a bad idea to update the DataVersion outside of MC, you never know what will happen in the future, and there may still be entities in the chunk (treasure rooms, strongholds, mineshafts...)

I'd say to scan the chunks dataversion before regenerating/explicitplacing a dungeon, and if it is 'old', then print a warning but optionally continue (maybe after requesting confirmation)

**Comment by JiFish** [comment]
> We can try updating the DataVersion tag ourselves for chunks we touch. In theory all the entities in those chunks are ours. That might avoid them being mishandled by MC. I don't know if this will take some modification of PyMcLevel.

No modification of pymclevel should be needed, we could set the tag the same way you can fetch biome data. i.e
        chunk = level.getChunk(x,z)
        chunk.root_tag["DataVersion"] = ...

But I am not sure it is a safe thing to do. We don't know what other changes have and will be made.

**Comment by orphu** [comment]
If we don't fix the DataVersion, then there's no way we can generate in a chunk unless it passes through MC first. 

As JiFish said, I do wonder how MCEdit handles it.

**Comment by JiFish** [comment]
Thinking about it, they probably don't. MCEdit is mostly 'blind' to the in-game data. (If it wasn't pymclevel would probably have some of the entity creating utilities that you built.) Someone creating villagers and other complex entities probably uses a filter or does it in-game with commands.

**Comment by JiFish** [comment]
So I just did a little fly around in 1.9 using my old test world. Generated a dungeon as was greeted by a villager. Just in case there was any doubt left.

**Comment by orphu** [comment]
Great, thanks!

**Comment by orphu** [comment]
The chunk DataVersion as of 1.9.2 appears to be 176. 

So, we can certainly exclude any chunks where DataVersion < a minimum supported value. But what then? The scenario is that someone upgrades MCD. If the min DataVersion is higher, the chunk cache is invalidated and rescanned. MCD reports no good chunks and exits. They won't be able to generate any dungeons. 

How do we instruct the user to fix this? IFAIK, there is no easy way for someone to update all the chunks on their map. I guess they could run it through one of the land generators that tweak the spawn point and repeatedly load a map. It's very cumbersome though.

**Comment by sshipway** [comment]
You probably only need to increment the minimum supported dataversion when there is a change incompatible with MCD.  So, you can likely have the minimum dataversion set to 111 as this covers spawners, signs, minecarts and frames/paintings.  If you start to use something that is no longer compatible, raise the minmum version appropriately.  After all, most people will upgrade to 1.9.x and be well ahead of this

If MCD runs and says "no compatible chunks" it should also output more information, such as "upgrade world chunks to latest version, here is a way to do it, this URL has documentation..."

Someone (looks about shiftily) needs to test to see if you can upgrade the chunk versions simply by using the WorldBorder bukkit plugin or the WorldGen Forge plugin.  I just don't have a  way to quickly identify the chunk versions, though.

**Comment by orphu** [comment]
I'm not sure that gets it. 

Been looking at this. As far as I can tell the chunk DV in 1.9.0 was 169, and in 1.9.2 it's now 176. That means there are seven patches added in two minor releases that could potentially break things. That's a lot!

Thing is, I have no idea what those seven patches change, so I have no idea whether or not they are important. What should the min DV be? I need to know what the changes are to tell if they break anything. Does anyone have a good source of what the individual DV patches change?

111 is probably too low. Or maybe it's not. Depends on what the next 65 patches did. We based the 0.15.0 release on 1.9.0 NBT specs, so 111 is in all likelihood too low since that was where things stood in a pre-1.9.0 snapshot. 

I'm still leaning towards setting the DV per chunk. Something like this:

* MCD identifies target chunks.
* MCD removes all entities and tile entities from the target chunks.  (This doesn't happen right now in all cases, but can. It does happen on regen and delete). This will prevent unpredictable behavior for NBTs that need to get patched, but don't. 
* MCD writes blocks, entity, and tile entities to the target chunks as part of the generation process. These are guaranteed to be compatible with the MC version that is our release target. 
* MCD sets the DV for that chunk to be that of the MC target version. 
* The map is loaded into MC
* MC only runs patches starting with the minimum DV when it loads these chunks. Other chunks not touched by MCD get the full upgrade treatment. 

Now in the v0.15.1 case, maybe we say the min DV is 169, since that was the value in 1.9.0 and we've not made any changes to accommodate NBT updates made in 1.9.1 or 1.9.2 (if any). If something changes in 1.9.3 we stay compatible since DV patches will be applied to our data. 

If we make updates for NBT changes in a future version, we bump the min DV to be equal to that release version.

**Comment by JiFish** [comment]
I've been unable to find a complete list of patches. You'd hope Mojang would maintain a list. :/

Given the changes we know about this seems pretty solid. The only concern I have is this method fail at some point in the future. For example, maybe they update both the way entities and biomes are stored between MC versions. Then we'd need to either update the biome data ourselves or fall back on the 'bad chunks' method.

I might be worried about nothing. Your solution is kinder on the user - they'd never need to know. And a situation like I described might never happen.

**Comment by sshipway** [comment]
A lack of (public) documentation of the DataVersions is a nuisance, but maybe this is the best you can do.  If you remove all the entities in the chunk when upgrading, this would remove all frames, minecarts, chests, armour stands as well and mobiles, but there will (probably) not be many of those.

**Comment by orphu** [comment]
Moved clearing out old entities from only regen to add as well. Set a minimum DV. As entity and tile entity tags change, we'll need to manually update this value.
