### ISSUE TITLE
Unknown Item: silver shulker box

### ISSUE THREAD

**Issue by Braleth** [orphu/mcdungeon#386]
Ran into the the following error trying to generate dungeons in a 1.11 world using mcdungeon-v0.17.0-win64: http://pastebin.com/e5x6juZg

Config info from materials.cfg: http://pastebin.com/Csi9VdsB

**Comment by JiFish** [comment]
This is likely due to insufficient testing on my part. Sorry about that. I will have a look at this as soon as I can.

**Comment by JiFish** [comment]
Thanks for the report, this will be fixed in the next version. In the meantime you can fix this problem by replacing the shops/atelier.cfg file. Right-click the following link and do a 'save as' and then replace the file in your current installation: [atelier.cfg](https://raw.githubusercontent.com/orphu/mcdungeon/3d84612d8102c2f6622061c17aee18a9146ba9a2/shops/atelier.cfg)
