### ISSUE TITLE
Wither Skeletons - Incorrect entity name

### ISSUE THREAD

**Issue by Braleth** [orphu/mcdungeon#387]
Wither skeleton spawners are not functioning due to an incorrect entity name (1.11 rename a fair amount of entities). Console output when you're within range of a spawner: http://pastebin.com/Y38kmEF5

New entity name should be wither_skeleton, not witherskeleton.

I checked all of the NBT files for the spawners and I don't see anything referencing "witherskeleton". As well, the default.cfg I'm using has two entries and they're both correctly set to "wither_skeleton".

**Comment by JiFish** [comment]
Thank you for the report. They might be hardcoded somewhere.

**Comment by JiFish** [comment]
I've pushed a fix for this that will be available in the next release. This bug is not harmful, but the console errors are annoying and it will make the crypt treasure room easier to raid. As a workaround, you can disable the crypt treasure room by setting the following in your config file in the `[treasure rooms]` section:
```
Crypt: 30
```

**Comment by Braleth** [comment]
Thanks a million for the quick fix. I've pulled down the phython version of MCD and I'm running it with the latest fixes (cave_spider as well).
