### ISSUE TITLE
Update entity building functions for 1.11/1.12 and make case-insensitive.

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#392]
Update entity building functions for 1.11/1.12 and make case-insensitive. Currently this isn't breaking anything, but needs to be fixed for future use.

**Comment by JiFish** [comment]
To eliminate the risk of someone repeating what I have already done, I have pushed my changes so far to an alternate branch. This code needs way more testing than I have currently put it through.

**Comment by orphu** [comment]
I've merged this into development to continue. I think this needs to be in the next release.

**Comment by JiFish** [comment]
Thanks for picking this up. Unfortunately, I simply didn't have the time to give this the proper testing it needed.

**Comment by orphu** [comment]
Hm, maybe. Right now spawners aren't generated by this code, but they could be. At the moment it's all handled with addspawner() and getspawnertags() in deungeon.py. Could (and probably should) move getspawnertras() in this this code. 

Would be nice if we could store NBT files as text to make them easier to deal with. #362 sounds problematic though. Maybe YAML instead of JSON...

**Comment by JiFish** [comment]
Is this complete?

**Comment by orphu** [comment]
I need to go through the recent release notes and make sure it's all covered.
