### ISSUE TITLE
Error using Windows version (v.0.18.0) generating Dungeons

### ISSUE THREAD

**Issue by LucianDevran** [orphu/mcdungeon#433]
Help!
I got an Error creating Dungeons using the Windows version (v0.18.0) on a Spigot 1.12.2 world. I have an rather big world changed my config and set Dungeoncount to 500. Level to 5-42. Maxsize both x and z to 4-30. Everything else is the same as in the config. 

The Error occurs on generating Dungeons. Its through the whole process of checking and everything (which takes me 4-5 hours everytime) and even generated 9 Dungeons before. So the Error occurs when generating the 10th Dungeon. 
Unlucky me tried to ctrl+a the console output but it closed obviously. I still managed to get the main part of the error. 
Its at generating/rendering rooms and was at around 60% but then i got the error my Dynmap looks like it has wierd chunks (I pregenerated with a wierd plugin first and then used bukkit world border to do so). If anyone knows a solution I would be very happy...

OS: WIndows 10 x64

Error: https://pastebin.com/xXXtksx2

Config: https://pastebin.com/xVh25j0H

Dynmap: EDIT: Deleted Dynmap due to massive harddrive usage 

I also posted this at the MinecraftForum site.

**Comment by JiFish** [comment]
Sorry, there's not really enough information to tell what is happening. MCDungeon is not tested with any mods, so that may well be the issue. Especially if we are dealing with altered terrain generation.

One the software has processed the map successfully, subsequent checks will be faster. So one work around might to be to generate fewer dungeons at time and backup between each attempt.

**Comment by LucianDevran** [comment]
Yeah i spotted missing chunks all over my world so that might be it. I use some plugins that modify Mobdrops but none that modifie world generation...

**Comment by JiFish** [comment]
> I pregenerated with a wierd plugin first and then used bukkit world border to do so

Some people have also had issues with pre-generated maps. Although, so long as you have `use_incomplete_chunks: False` in your config, it shouldn't cause a crash.

So yeah, try smaller runs. You might even be able to figure out a correlation between which dungeons do and don't work which could help narrow down the issue.

**Comment by LucianDevran** [comment]
So if I do smaller "runs" would it take 4-5 hours everytime checking chunks and stuff? Or would this be skipped?

**Comment by JiFish** [comment]
Once the software has done a complete scan on the world, it will store a cache inside the world's save directory which will speed up future runs. It should only need to scan chunks that have been added or changed since the last run.

**Comment by LucianDevran** [comment]
Ah Nice! It probably won´t work with the crashed copie of the world or will it?

**Comment by LucianDevran** [comment]
Yeah works with the crashed world

**Comment by LucianDevran** [comment]
https://pastebin.com/WUPgTBzH
Smaller run (only 10) worked
Also I noticed that most Dungeons (all despite 2) are 4x4x5 eventhough I set the values to be choosen from a much larger range.

**Comment by LucianDevran** [comment]
Got an Error creating treasure hunts... => https://pastebin.com/2G9AfnQ2
It worked now several times with dungeons! Thanks for the advice

**Comment by JiFish** [comment]
The number of incomplete chunks you are getting is too high. `Incomplete: 1169248`. This probably due to you generating the chunks with worldborder, which doesn't properly mark them as complete. In other words with your current setup MCDungeon is only able to place dungeons in chunks that _weren't_ generated by worldborder. This might be why you aren't seeing any big dungeons.

It's also worth noting that a 30x30 chunk dungeon is HUGE - almost a quarter of a square kilometer. You might want to pick a smaller value.

Your options are to a) Generate the chunks a different way. Some suggestions have been posted on the forum thread, though I am not sure how up to date they are or b) switch on use_incomplete_chunks and risk more crashes.

> Got an Error creating treasure hunts... => https://pastebin.com/2G9AfnQ2

It looks like there is a problem writing to the files on the disk. Are you accessing the world files in another bit of software while generation is ongoing?

**Comment by LucianDevran** [comment]
> It looks like there is a problem writing to the files on the disk. Are you accessing the world files in another bit of software while generation is ongoing?

No everthing closed except the folder of McDungeon and the console and my browser....

If i switch use_incomplete_chunks on and it crashes will I be able to open the world again or will the world be corrupted? 
I found someone using commandblocks : https://youtu.be/ak3MRPaXOaQ
And a programm which Im not sure how to use: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/2619797-nocturne-a-tool-for-generating-java-deobfuscation

**Comment by JiFish** [comment]
> If i switch use_incomplete_chunks on and it crashes will I be able to open the world again or will the world be corrupted?

In theory, yes. But no guarantees. Always keep a backup.

**Comment by LucianDevran** [comment]
Ok I will try to do the use_incomplete_chunks first if it crashes or the outcome is not what we expected i will  use the Commandblock method to generate the map.
Thanks for your help so far

**Comment by LucianDevran** [comment]
Yeah worked! Most of the dungeons are still 4x4x5 but I know get fairly more different sized Dungeons.
Also I haven´t run in any errors
